### ISSUE TITLE
We should add package-lock.json to the repo  

### ISSUE THREAD

**Issue by anasdox** [linkedtales/scrapedin-linkedin-crawler#18]
Hi, thank you for sharing :)

I got the following error when i start the crawler 

```
npm start

scrapedin-crawler@0.0.2 start /home/anas/Tools/scrapedin-linkedin-crawler
node src/index

scrapedin: 2019-10-17T13:52:01.937Z info: [scrapedin] initializing
scrapedin: 2019-10-17T13:52:03.192Z info: [scrapedin] email and password was provided, we're going to login...
(node:6249) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.deleteCookies): Invalid parameters name: string value expected
    at Promise (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page.deleteCookie (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:395:26)
    at Page.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.setCookie (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:413:16)
    at Page.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/scrapedin/src/openPage.js:16:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6249) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at Promise (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/scrapedin/src/openPage.js:24:14)
  -- ASYNC --
    at Frame.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/home/anas/Tools/scrapedin-linkedin-crawler/node_modules/scrapedin/src/openPage.js:24:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`
```

Could you provide the package-lock.json to be sure to get the same dependencies please.

Thanks

**Comment by leonardiwagner** [comment]
Hi @anasdox this was a bug from scrapedin v1.0.9, thank you for reporting this! Solutions:

- update the scrapedin version from `1.0.9` to `1.0.10` on `package.json`
or
- manually fix the `/node_modules/scrapedin/login.js` with the [bugfix](https://github.com/linkedtales/scrapedin/commit/551e3a8894261bd9b2621be44396ef64395e626e#diff-e92d6692c88fc94484d8df419a8a1afdL6)

please report if it works, thank you

**Comment by anasdox** [comment]
Thanks @leonardiwagner
