### ISSUE TITLE
Retry the request if failed 

### ISSUE THREAD

**Issue by anasdox** [linkedtales/scrapedin-linkedin-crawler#20]
Hello,

After some good crawling request, I got the following error :

```
scrapedin: 2019-10-18T09:03:38.320Z error: [cleanMessageData] LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
2019-10-18T09:03:38.321Z error: error on crawling profile: https://www.linkedin.com/in/xxxxxxx/ 
 Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
(node:29800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at crawl (/home/anas/workspace/scrapedin-linkedin-crawler/src/crawler.js:26:71)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:29800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
We should add a retries configurable feature to avoid such problem.

**Comment by leonardiwagner** [comment]
Hi @anasdox , I just fixed that: https://github.com/linkedtales/scrapedin-linkedin-crawler/pull/23/files

you can either do a `git pull`  or apply those changes manually in your code, thanks
