### ISSUE TITLE
TimeoutError: waiting for selector "#login-email" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by isbkch** [linkedtales/scrapedin-linkedin-crawler#3]
On mac, I followed everything, chromium is opened but I get this error after a while

```
(node:3042) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "#login-email" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/DOMWorld.js:444:17)
    at Frame.waitForSelector (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/FrameManager.js:628:47)
    at Frame.<anonymous> (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/helper.js:111:23)
    at Frame.waitFor (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/FrameManager.js:613:19)
    at Page.waitFor (/Users/myname/Downloads/linkedinCrawler/node_modules/puppeteer/lib/Page.js:1037:29)
    at module.exports (/Users/myname/Downloads/linkedinCrawler/node_modules/scrapedin/src/login.js:10:14)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:3042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Btw, the opened Linkedin page is not resized and the login button is hidden in the far right side, I'm testing on a 13" mac book air so it's not visible

**Comment by Nowhy** [comment]
in windows, same issues.....

**Comment by venturaEffect** [comment]
It seems I'm on the same issue using Linux...

LinkedIn page opens telling that automated software is in chrome.

Adding terminal error lines:

```
npm start

> scrapedin-crawler@0.0.2 start /home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master
> node src/index

(node:27893) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "#login-email" failed: timeout 30000ms exceeded
    at new WaitTask (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/DOMWorld.js:444:17)
    at Frame.waitForSelector (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/FrameManager.js:628:47)
    at Frame.<anonymous> (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/helper.js:111:23)
    at Frame.waitFor (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/FrameManager.js:613:19)
    at Page.waitFor (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/puppeteer/lib/Page.js:1037:29)
    at module.exports (/home/zaesar/Escritorio/scrapedin/scrapedin-linkedin-crawler-master/node_modules/scrapedin/src/login.js:10:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:27893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by venturaEffect** [comment]
1. Have downgraded puppeteer like `sudo apt-get install puppeteer=1.13.0`
2. Have reinstalled chromium
3. Have done that too https://github.com/GoogleChrome/puppeteer/issues/404#issuecomment-323555784
4. Have opened manually my account on chromium. 

Start npm again and opens window smaller than the web with no option to sign in...

Any help will be really appreciated :)

**Comment by TianqiGeng** [comment]
in windows, same issues....
![$3020348A14B74ED9](https://user-images.githubusercontent.com/19911984/61777722-fa724700-ae2f-11e9-8be3-971028de222f.jpg)

**Comment by leonardiwagner** [comment]
@tinash we don't find for `#uc.user_0` , have you modified to search for this content?

Please post the whole error stack, the most important part of this error is about when happened in the scrapedin code. Thank you.

**Comment by TianqiGeng** [comment]
Hi @leonardiwagner , thanks for your replay
![$4ADECC906730D92C](https://user-images.githubusercontent.com/19911984/61932806-da20c480-afb6-11e9-8e92-c51e09cf1e89.jpg)
this is the code, I want to log in to the website and close the page.

`
const puppeteer = require('puppeteer');
(async () => {
    
    const browser = await puppeteer.launch({
        headless: false,
        //对网站加信任
          ignoreHTTPSErrors: true, 
          args: ['--disable-setuid-sandbox', '--no-sandbox', '--enable-features=NetworkService']});

      const page = await browser.newPage();
     
      console.log("进入页面");

      
      await page.goto('https://158.175.108.217/console', 
      {waitUntil: 'networkidle2'});
      console.log("用户名和密码");
      await page.waitFor(1500);
      await page.waitForSelector('#uc.user_0');
      
    //   await page.waitForSelector('#uc.user_0',{timeout:4000});

    //   await page.focus('#uc.user_0');
    //   await page.waitFor(500);
    //   await page.type('#uc.user_0', 'xxxx',);

    //   await page.focus('#uc.password_0');
    //   await page.waitFor(500);
    //   await page.type('#uc.password_0', 'xxxxxx', );

    //   await page.waitFor(500);
    //   await page.click('.LoginForm-loginbtn-35242 bx--btn bx--btn--primary bx--btn--disabled')
    //   console.log("离开页面");
      // browser.close(); 
})().catch(error => console.log('caught', error));
`

![$7ECD92627076B4BF](https://user-images.githubusercontent.com/19911984/61932969-43083c80-afb7-11e9-83f0-3b7473c5caa0.jpg)

**Comment by leonardiwagner** [comment]
Hi @tinashime , you are going to "https://158.175.108.217/console" URL, what is that?

It's better to login at linkedin at `/login` instead their `/` website, since it changes sometimes, this is the page what I got on `/login`:

![Screenshot from 2019-07-26 12-27-56](https://user-images.githubusercontent.com/2164551/61962934-10ebe000-afa1-11e9-8463-ae43a12a28ff.png)


Since what you are reporting is not about this project code itself, I'm going to close this issue, but feel free to ask more questions or re-open the issue if necessary!
