### ISSUE TITLE
Error: net::ERR_INTERNET_DISCONNECTED at https://www.linkedin.com/login

### ISSUE THREAD

**Issue by cyanide2019** [linkedtales/scrapedin-linkedin-crawler#30]
I got this error under centos 7 , this crawler was able to work but it throw the following error after I change my place to work , so any one has some idea ？

(node:6378) UnhandledPromiseRejectionWarning: Error: net::ERR_INTERNET_DISCONNECTED at https://www.linkedin.com/login
    at navigate (/home/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/home/scrapedin-linkedin-crawler/node_modules/scrapedin/src/openPage.js:24:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leonardiwagner** [comment]
@cyanide2019 could you try using cookies instead login? https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login

**Comment by cyanide2019** [comment]
hi leo , since I am very new to cookie , which part of the chrome cookie
should I copy to the config.json ? can you provide a sample for that cookie
format ？ thanks lot

**Comment by leonardiwagner** [comment]
@cyanide2019 everything which the extension exports, which it's around 200-350 lines

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
