### ISSUE TITLE
happy new year , and I got this unhandledPromiseRejectionERROR

### ISSUE THREAD

**Issue by cyanide2019** [linkedtales/scrapedin-linkedin-crawler#35]
we're going to login...
(node:5154) UnhandledPromiseRejectionWarning: Error: net::ERR_INTERNET_DISCONNECTED at https://www.linkedin.com/login
    at navigate (/home/tony/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/tony/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/tony/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/tony/scrapedin-linkedin-crawler/node_modules/puppeteer/lib/helper.js:112:23)
    at module.exports (/home/tony/scrapedin-linkedin-crawler/node_modules/scrapedin/src/openPage.js:26:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------------

NOT SURE IT IS THE NODE PROBLEM OR WHAT 

THANKS

**Comment by cyanide2019** [comment]
it was network issue....
